### ISSUE TITLE
Tricks that work

### ISSUE THREAD

**Issue by asuith** [SZLSP/reid2020NAIC#12]
## Works

Color Jittering
```yaml
INPUT:
  CJ:
    PROB: 0.5
    ENABLED: True
```

## NOT work

```yaml
INPUT:
  REA:
    ENABLED: false
```
